### ISSUE TITLE
Issues with Biomes of Plenty Alps

### ISSUE THREAD

**Issue by tillasiren** [InspectorCaracal/BetterBeekeeping#1]
I have noticed that with both this mod and Biomes of plenty I was unable to keep bees in the Alps (they would get a hive up to 3 maybe 4 but then never fill it) I did test this for a few hours to ensure that it was happening. Multiple worlds and clients were used to test this. 
Myself and a Dev form the BoP Discord believe this is due to the "seasons compatibility" but I did not have any mod for seasons installed on any client. In a client without this mod present the bees behaved just fine and filled the hive at a reasonable speed.

**Comment by InspectorCaracal** [comment]
I realize this is an extremely late response so there's probably no point, but:

This is a configurable behavior, not a bug. You can set `hibernate` to false in the mod's config file to allow bees to be active in cold weather and climates.
