### ISSUE TITLE
1.18.2 port (forge)

### ISSUE THREAD

**Issue by xFirefalconx** [InspectorCaracal/BetterBeekeeping#2]
Hi, 
would love to have this mod in 1.18.2. Is there any possibility/plan on a port to that version?

**Comment by InspectorCaracal** [comment]
No plans, but there might be a possibility. I'll take a look at how much work it would be.

**Comment by darthvader45** [comment]
Yeah, same with 1.19.3, but it's fine if not.  I can do without bee stuff for the time being.

**Comment by InspectorCaracal** [comment]
Currently working on updating this for both 1.18 and 1.19!

**Comment by xFirefalconx** [comment]
That sounds awesome, thank you! I could do some large scale tests on incompatibilities once it's out, since I plan to implement it in my modpack update soon! I'd love to get an update once it's out, is that possible? :D

**Comment by InspectorCaracal** [comment]
@xFirefalconx Sure! Do you want me to ping you for 1.18.2 still or have you moved to 1.19?

**Comment by xFirefalconx** [comment]
1.18.2, please, I don't use 1.19+, thanks!

**Comment by InspectorCaracal** [comment]
*edit*

GOOD news! Thanks to `Random` on the Forge discord, I got beehives working in 1.18 too, so it's only a matter of time now

**Comment by darthvader45** [comment]
Wait, you found a solution?  Last I heard via email noti, you were running into an issue.  Glad to hear it's fixed.  Hopefully 1.19 can come soon, as I need a harmless smoker for my bees.

**Comment by InspectorCaracal** [comment]
@darthvader45 Yep! Someone on the discord was super helpful and gave me the missing piece I need, so I'm just doing a last bit of cleanup for 1.18, and 1.19 will be ready as soon as I finish making the new Mangrove beehive

**Comment by InspectorCaracal** [comment]
@xFirefalconx 1.18.2 version is up on curseforge!

**Comment by xFirefalconx** [comment]
Thanks! I'll download it and test it in my modpack right away! Will let you know if there happen to be issues

**Comment by InspectorCaracal** [comment]
@darthvader45 The 1.19.2 version is submitted and should be available on curseforge within the hour as well 👍 

This issue is now Resolved

**Comment by darthvader45** [comment]
Awesome!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
