### ISSUE TITLE
BUG: Wither Rose bees do not produce Strange Honey

### ISSUE THREAD

**Issue by KoboldCatgirl** [InspectorCaracal/BetterBeekeeping#3]
[I am using Forge with version 1.18.2]

Hi there! To be very concise, as far as I can tell, while bees _can_ sometimes pollinate wither roses (assuming you keep them alive, of course), the product you get is ordinary default honey.

I tested by encasing a number of spawned bees in a glass dome with a bee box that was blocked off from all other sides. I am not 100% certain of my testing methods (I noticed a single glass pane that already-pollinated baby bees could have hypothetically squeezed through to get in, so it's possible the test was contaminated), and I may attempt to test it again tomorrow just to be sure. That being said, I wanted to bring it to your attention.

As a sidenote, it's extremely challenging to test this without knowing commands to give the bees invulnerability, especially since beekeeping is a slow job regardless. I wound up using a dispenser with a clock to launch lingering Regen potions in every five seconds, which feels a lot less "small beekeeping-y" than the mod seemed to intend and seems like it could be exorbitantly expensive in Vanilla, so I can't tell if I'm doing something wrong.

**Comment by InspectorCaracal** [comment]
Thanks for the report! I admit, I haven't specifically tested wither roses in-game for all the reasons you described, but I did add it while knowing it would be extremely difficult to actually obtain. Which makes it all the more important it actually works! I'll see if I can replicate the issue (although it'll have to be late next week) and keep this issue updated.

**Comment by InspectorCaracal** [comment]
@KoboldCatgirl Oh, and just to check off all my boxes:

- Which beehive variety were you using?
- How many bees were in it?
- Are you running any other mods that might affect bees or flowers? (Texture packs don't count, don't worry about any of those)

**Comment by KoboldCatgirl** [comment]
Hi there! I figured out how to do invulnerable bees and ran the test again today. Barring some weird "bees that take damage count as having pollinated default flowers" glitch, I believe I can safely call this a false alarm, and apologize for any confusion or wasted time this may have caused!

There are some other bee- and flower-related mods installed, but since the test was a success, I'm not too fussed digging them out unless it'd be of use to you!

In case you're curious:
![Image](https://github.com/InspectorCaracal/BetterBeekeeping/assets/143960193/b3d220da-e9c9-453a-a144-8b24732868cb)
_Three wither rose enclosures and a control group orchid enclosure, with 6-7 invulnerable bees and all other access points fastidiously blocked off. Birch boxes._
![image](https://github.com/InspectorCaracal/BetterBeekeeping/assets/143960193/54b5397c-3c6f-495e-9f7d-fee66d51ffba)
_Three wither roses and seven very determined bees. (Three are inside already.)_
![image](https://github.com/InspectorCaracal/BetterBeekeeping/assets/143960193/a7bf0789-0449-4e93-97da-3b5a1f287c07)
_A very brave survivor of the previous Wither Rose Trials. I gave her a nice new bee box and some tulips._
![image](https://github.com/InspectorCaracal/BetterBeekeeping/assets/143960193/9a554d11-b4d2-4cac-a765-295dd5f66f1f)
_Wither rose enclosures, with Strange Honey!_
![image](https://github.com/InspectorCaracal/BetterBeekeeping/assets/143960193/4edf8890-4696-46dc-9625-f9ef749bbf60)
_And the control group, of course._

**Comment by InspectorCaracal** [comment]
No worries, I'm just glad to hear it's working! And thank you for the pictures :D
